package runtime

// workflow.go implements the durable plan/tool loop executed inside a workflow engine.
//
// Contract:
// - The workflow loop is deterministic and replay-safe: timeouts use workflow time.
// - The loop publishes lifecycle and tool events via hooks for streaming and persistence.
// - Helper methods in sibling workflow_*.go files are invoked by this loop; callers should
//   not call them directly outside of workflow execution.

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/CaliLuke/loom-mcp/runtime/agent/engine"
	"github.com/CaliLuke/loom-mcp/runtime/agent/hooks"
	"github.com/CaliLuke/loom-mcp/runtime/agent/interrupt"
	"github.com/CaliLuke/loom-mcp/runtime/agent/model"
	"github.com/CaliLuke/loom-mcp/runtime/agent/planner"
	"github.com/CaliLuke/loom-mcp/runtime/agent/policy"
	"github.com/CaliLuke/loom-mcp/runtime/agent/run"
	"github.com/CaliLuke/loom-mcp/runtime/agent/telemetry"
)

const (
	// Minimal viable timeout for scheduling an activity. If remaining time is
	// less than or equal to this value, the runtime should not schedule new work.
	minActivityTimeout = 3 * time.Second

	// Minimal viable grace period for finalization. If remaining time is
	// less than or equal to this value, the runtime should finalize with a user-facing message.
	defaultFinalizerGrace = 10 * time.Second
)

// ExecuteWorkflow is the main entry point for the generated workflow handler.
//
// Advanced & generated integration
//   - Intended to be invoked by code generated by loom-mcp during agent
//     registration, or by advanced users writing custom engine adapters.
//   - Normal applications should prefer the high‑level AgentClient API
//     (Runtime.Client(...).Run/Start) rather than calling this directly.
//
// It executes the agent's plan/tool loop using the configured planner, policy,
// and runtime hooks. Returns the final agent output or an error if the workflow
// fails. Generated code calls this from the workflow handler registered with
// the engine.
func (r *Runtime) ExecuteWorkflow(wfCtx engine.WorkflowContext, input *RunInput) (_ *RunOutput, retErr error) {
	defer func() {
		retErr = hooks.WrapRunCompletionError(retErr)
	}()
	r.logWorkflowStart(wfCtx, input)
	if err := validateWorkflowInput(input); err != nil {
		return nil, err
	}
	defer func() {
		r.storeWorkflowHandle(input.RunID, nil)
		if r.reminders != nil {
			r.reminders.ClearRun(input.RunID)
		}
	}()
	reg, ok := r.agentByID(input.AgentID)
	if !ok {
		return nil, fmt.Errorf("agent %q is not registered", input.AgentID)
	}
	r.logger.Info(wfCtx.Context(), "Agent found, executing plan activity", "agent_id", input.AgentID)
	ctrl := interrupt.NewController(wfCtx)
	runCtx := workflowRunContext(input)
	turnID := input.TurnID
	if err := r.publishInitialWorkflowEvents(wfCtx.Context(), input, runCtx, turnID); err != nil {
		return nil, err
	}
	finalStatus := runStatusSuccess
	var finalErr error
	defer r.publishWorkflowCompletion(wfCtx, input, turnID, &finalStatus, &finalErr)

	planInput, startReq, timing, deadlines := r.prepareWorkflowPlanning(wfCtx, reg, input, runCtx)
	if err := enforcePlanActivityInputBudget(startReq); err != nil {
		finalErr = err
		finalStatus = runStatusFailed
		return nil, err
	}
	planOpts := r.resolveAndLogWorkflowTiming(wfCtx, reg, input, timing)
	if err := r.publishPlanningPhase(wfCtx.Context(), input, turnID); err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	firstOutput, err := r.runInitialPlan(wfCtx, reg, startReq, planOpts, deadlines.Hard)
	if err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	result := firstOutput.Result
	caps, nextAttempt, parentTracker, err := r.prepareWorkflowLoopState(wfCtx.Context(), reg, input, planInput, result)
	if err != nil {
		finalErr = err
		finalStatus = runStatusFailed
		return nil, err
	}
	r.logger.Info(wfCtx.Context(), "Starting runLoop", "tool_calls", len(result.ToolCalls))
	if err := r.publishExecutionPhase(wfCtx.Context(), input, turnID); err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	out, err := r.runLoop(
		wfCtx,
		reg,
		input,
		planInput,
		firstOutput.Result,
		firstOutput.Transcript,
		firstOutput.Usage,
		caps,
		deadlines.Budget,
		deadlines.Hard,
		nextAttempt,
		turnID,
		parentTracker,
		ctrl,
		timing.FinalizerGrace,
	)
	if err != nil {
		finalErr = err
		finalStatus = terminalRunStatusForError(err)
		return nil, err
	}
	// Successful completion.
	finalStatus = runStatusSuccess
	finalErr = nil
	return out, nil
}

func validateWorkflowInput(input *RunInput) error {
	if input.AgentID == "" {
		return errors.New("agent id is required")
	}
	return nil
}

func (r *Runtime) logWorkflowStart(wfCtx engine.WorkflowContext, input *RunInput) {
	if r.logger != nil {
		r.logger.Info(wfCtx.Context(), "ExecuteWorkflow called", "agent_id", input.AgentID, "run_id", input.RunID)
	}
}

func workflowRunContext(input *RunInput) run.Context {
	return run.Context{
		RunID:            input.RunID,
		SessionID:        input.SessionID,
		TurnID:           input.TurnID,
		ParentToolCallID: input.ParentToolCallID,
		ParentRunID:      input.ParentRunID,
		ParentAgentID:    input.ParentAgentID,
		Tool:             input.Tool,
		ToolArgs:         input.ToolArgs,
		Attempt:          1,
		Labels:           input.Labels,
	}
}

func (r *Runtime) publishInitialWorkflowEvents(ctx context.Context, input *RunInput, runCtx run.Context, turnID string) error {
	if err := r.publishHook(ctx, hooks.NewRunStartedEvent(input.RunID, input.AgentID, runCtx, *input), turnID); err != nil {
		return err
	}
	return r.publishHook(ctx, hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhasePrompted), turnID)
}

func (r *Runtime) publishWorkflowCompletion(
	wfCtx engine.WorkflowContext,
	input *RunInput,
	turnID string,
	finalStatus *string,
	finalErr *error,
) {
	phase := terminalRunPhaseForStatus(*finalStatus)
	detached := wfCtx.Detached()
	termCtx, cancel := context.WithTimeout(detached.Context(), 10*time.Second)
	defer cancel()
	if err := r.publishHookErr(
		termCtx,
		hooks.NewRunCompletedEvent(input.RunID, input.AgentID, input.SessionID, *finalStatus, phase, *finalErr),
		turnID,
	); err != nil {
		r.logWarn(termCtx, "run completed hook failed", err, "run_id", input.RunID, "agent_id", input.AgentID)
	}
}

func (r *Runtime) prepareWorkflowPlanning(
	wfCtx engine.WorkflowContext,
	reg AgentRegistration,
	input *RunInput,
	runCtx run.Context,
) (*planner.PlanInput, PlanActivityInput, runTiming, runDeadlines) {
	planInput := &planner.PlanInput{Messages: input.Messages, RunContext: runCtx}
	timing := resolveRunTiming(reg, input)
	deadlines := runDeadlines{FinalizerGrace: timing.FinalizerGrace}
	if timing.TimeBudget > 0 {
		deadlines.Budget = wfCtx.Now().Add(timing.TimeBudget)
		deadlines.Hard = deadlines.Budget.Add(timing.FinalizerGrace)
	}
	return planInput, PlanActivityInput{
		AgentID:    input.AgentID,
		RunID:      input.RunID,
		Messages:   input.Messages,
		RunContext: runCtx,
	}, timing, deadlines
}

func (r *Runtime) resolveAndLogWorkflowTiming(
	wfCtx engine.WorkflowContext,
	reg AgentRegistration,
	input *RunInput,
	timing runTiming,
) engine.ActivityOptions {
	planOpts := reg.PlanActivityOptions
	if input.Policy != nil && input.Policy.PlanTimeout > 0 {
		planOpts.StartToCloseTimeout = input.Policy.PlanTimeout
	}
	if r.logger != nil {
		toolTimeout := reg.ExecuteToolActivityOptions.StartToCloseTimeout
		if toolTimeout == 0 {
			toolTimeout = defaultExecuteToolActivityTimeout
		}
		if input.Policy != nil && input.Policy.ToolTimeout > 0 {
			toolTimeout = input.Policy.ToolTimeout
		}
		r.logger.Info(wfCtx.Context(), "timing_resolved",
			"time_budget", timing.TimeBudget,
			"finalizer_grace", timing.FinalizerGrace,
			"hard_deadline", func() time.Time {
				if timing.TimeBudget <= 0 {
					return time.Time{}
				}
				return wfCtx.Now().Add(timing.TimeBudget + timing.FinalizerGrace)
			}(),
			"plan_timeout", planOpts.StartToCloseTimeout,
			"tool_timeout", toolTimeout,
		)
	}
	return planOpts
}

func (r *Runtime) publishPlanningPhase(ctx context.Context, input *RunInput, turnID string) error {
	return r.publishHook(ctx, hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhasePlanning), turnID)
}

func (r *Runtime) validateFirstPlanOutput(ctx context.Context, output *PlanActivityOutput) error {
	if output == nil || output.Result == nil {
		r.logger.Error(ctx, "Plan activity returned nil result")
		return fmt.Errorf("plan activity returned nil result")
	}
	r.logger.Info(ctx, "Plan activity completed", "tool_calls", len(output.Result.ToolCalls), "final_response", output.Result.FinalResponse != nil)
	return nil
}

func (r *Runtime) runInitialPlan(
	wfCtx engine.WorkflowContext,
	reg AgentRegistration,
	startReq PlanActivityInput,
	planOpts engine.ActivityOptions,
	hardDeadline time.Time,
) (*PlanActivityOutput, error) {
	firstOutput, err := r.runPlanActivity(wfCtx, reg.PlanActivityName, planOpts, startReq, hardDeadline)
	if err != nil {
		r.logger.Error(wfCtx.Context(), "Plan activity failed", "error", err)
		return nil, err
	}
	if err := r.validateFirstPlanOutput(wfCtx.Context(), firstOutput); err != nil {
		return nil, err
	}
	return firstOutput, nil
}

func applyWorkflowCaps(caps policy.CapsState, input *RunInput) policy.CapsState {
	if input.Policy == nil {
		return caps
	}
	if input.Policy.MaxToolCalls > 0 {
		caps.MaxToolCalls = input.Policy.MaxToolCalls
		caps.RemainingToolCalls = input.Policy.MaxToolCalls
	}
	if input.Policy.MaxConsecutiveFailedToolCalls > 0 {
		caps.MaxConsecutiveFailedToolCalls = input.Policy.MaxConsecutiveFailedToolCalls
		caps.RemainingConsecutiveFailedToolCalls = input.Policy.MaxConsecutiveFailedToolCalls
	}
	return caps
}

func (r *Runtime) publishExecutionPhase(ctx context.Context, input *RunInput, turnID string) error {
	return r.publishHook(ctx, hooks.NewRunPhaseChangedEvent(input.RunID, input.AgentID, input.SessionID, run.PhaseExecutingTools), turnID)
}

func (r *Runtime) prepareWorkflowLoopState(
	ctx context.Context,
	reg AgentRegistration,
	input *RunInput,
	planInput *planner.PlanInput,
	result *planner.PlanResult,
) (policy.CapsState, int, *childTracker, error) {
	if len(result.ToolCalls) == 0 && result.FinalResponse == nil && result.Await == nil {
		return policy.CapsState{}, 0, nil, fmt.Errorf("plan result has no tool calls, final response, or await")
	}
	if len(result.ToolCalls) == 0 && result.FinalResponse != nil {
		r.logger.Info(ctx, "PlanResult has FinalResponse but no ToolCalls - workflow will return early")
	}
	caps := applyWorkflowCaps(initialCaps(reg.Policy), input)
	var parentTracker *childTracker
	if planInput.RunContext.ParentToolCallID != "" {
		parentTracker = newChildTracker(planInput.RunContext.ParentToolCallID)
	}
	return caps, planInput.RunContext.Attempt + 1, parentTracker, nil
}

// runLoop executes the plan/tool/resume cycle until the planner returns a final response
// or a cap/deadline is exceeded. The turnID parameter enables turn-based event stamping.
func (r *Runtime) runLoop(
	wfCtx engine.WorkflowContext,
	reg AgentRegistration,
	input *RunInput,
	base *planner.PlanInput,
	initialResult *planner.PlanResult,
	initialTranscript []*model.Message,
	initialUsage model.TokenUsage,
	caps policy.CapsState,
	budgetDeadline time.Time,
	hardDeadline time.Time,
	nextAttempt int,
	turnID string,
	parentTracker *childTracker,
	ctrl *interrupt.Controller,
	finalizerGrace time.Duration,
) (*RunOutput, error) {
	if base == nil {
		return nil, errors.New("base plan input is required")
	}
	ctx := wfCtx.Context()
	if r.logger == nil {
		r.logger = telemetry.NoopLogger{}
	}
	if initialResult == nil {
		return nil, fmt.Errorf("runLoop initial PlanResult is nil")
	}
	if len(initialResult.ToolCalls) == 0 && initialResult.FinalResponse == nil && initialResult.Await == nil {
		return nil, fmt.Errorf("runLoop initial PlanResult has no ToolCalls, FinalResponse, or Await")
	}
	r.logger.Info(ctx, "runLoop starting iteration", "tool_calls", len(initialResult.ToolCalls), "final_response", initialResult.FinalResponse != nil, "await", initialResult.Await != nil)
	st := newRunLoopState(initialResult, initialTranscript, initialUsage, caps, nextAttempt)
	// Expose provider-ready messages via a workflow query for external rehydration.
	if err := wfCtx.SetQueryHandler("ledger_messages", func() ([]*model.Message, error) {
		return st.Ledger.BuildMessages(), nil
	}); err != nil {
		return nil, err
	}
	// Derive per-run overrides for Resume and Tools.
	resumeOpts := reg.ResumeActivityOptions
	if input.Policy != nil && input.Policy.PlanTimeout > 0 {
		resumeOpts.StartToCloseTimeout = input.Policy.PlanTimeout
	}
	toolOpts := reg.ExecuteToolActivityOptions
	if input.Policy != nil && input.Policy.ToolTimeout > 0 {
		toolOpts.StartToCloseTimeout = input.Policy.ToolTimeout
	}
	if toolOpts.StartToCloseTimeout == 0 {
		toolOpts.StartToCloseTimeout = defaultExecuteToolActivityTimeout
	}

	loop := newWorkflowLoop(
		r,
		wfCtx,
		reg,
		input,
		base,
		st,
		turnID,
		ctrl,
		parentTracker,
		runDeadlines{
			Budget:         budgetDeadline,
			Hard:           hardDeadline,
			FinalizerGrace: finalizerGrace,
		},
		resumeOpts,
		toolOpts,
	)
	return loop.run()
}

// timeoutUntil returns the remaining duration until deadline, relative to now.
// The ok result is false when deadline is non-zero and has already elapsed.
func timeoutUntil(deadline, now time.Time) (time.Duration, bool) {
	if deadline.IsZero() {
		return 0, true
	}
	rem := deadline.Sub(now)
	if rem <= 0 {
		return 0, false
	}
	return rem, true
}
