version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1001"
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    unparam:
      check-exported: true
  exclusions:
    generated: strict
    paths:
      - design/*
      - diagram/*
      - gql/*
      - mocks/*
      - codegen/agent/tests/testscenarios/*
    rules:
      - path: _test\.go
        linters:
          - dupl
